### PR TITLE
Add the Cascadia Code font.

### PR DESCRIPTION
**Pull request by lazerl0rd**
Signed-off-by: Diab Neiroukh <lazerl0rd@thezest.dev>

### CODE REVIEW

**Comment by Grimler91** [comment]
Please add an entry for cascadia to [setup-nerd-fonts.sh](https://github.com/termux/termux-styling/blob/master/setup-nerd-fonts.sh) as well, so that we can keep it up to date

**Comment by Finii** [comment]
> Please add an entry for cascadia to [setup-nerd-fonts.sh](https://github.com/termux/termux-styling/blob/master/setup-nerd-fonts.sh)

As far as I can see this PR actually adds `Cascadia Code` and not `Caskaydia Code` which is the Nerd Fonts patched version.
So it has nothing to do with `setup-nerd-fonts.sh` ;-)

**Comment by Finii** [comment]
Plus: The font file is ... rather old

image

Microsoft is at [2111.01](https://github.com/microsoft/cascadia-code/releases) already (not 2009.02).

**Comment by Grimler91** [comment]
@Finii Isn't this: https://github.com/ryanoasis/nerd-fonts/tree/master/src/unpatched-fonts/CascadiaCode microsoft's Cascadia Code? The one there is even older though (2007)

**Pull request merged**
